discovery.uri=http://coordinator:8082
presto.version=0.297-SNAPSHOT-b238a23
http-server.http.port=7778
shutdown-onset-sec=1
system-memory-gb=10
runtime-metrics-collection-enabled=true
exchange.http-client.enable-connection-pool=false
