coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8082
discovery-server.enabled=true
discovery.uri=http://coordinator:8082
presto.version=0.297-SNAPSHOT-b238a23

query.max-memory=500GB
query.max-total-memory=500GB

# 或者更细粒度的控制
exchange.http-client.read-timeout=30s
exchange.http-client.connect-timeout=10s

native-execution-enabled=true
optimizer.optimize-hash-generation=false
regex-library=RE2J
use-alternative-function-signatures=true

node-scheduler.max-splits-per-node=300
# node-scheduler.max-pending-splits-per-task=32
# node-scheduler.max-splits-per-task=96
node-scheduler.max-pending-splits-per-task=300
node-scheduler.max-splits-per-task=300

query.min-schedule-split-batch-size=300
