# coordinator=true
# node-scheduler.include-coordinator=true //也可以设成true，相当于会用coordinator计算
# http-server.http.port=8082
# discovery-server.enabled=true
# discovery.uri=http://coordinator:8082

# optimizer.optimize-hash-generation=false
# query.execution-policy=phased
# # 每个节点上单个查询可用的最大用户内存
# query.max-memory-per-node=2GB

# # 每个节点上单个查询可用的最大总内存（用户内存 + 系统内存）
# query.max-total-memory-per-node=3GB

# # 堆预留内存（用于缓冲区、线程栈等）
# memory.heap-headroom-per-node=1GB



coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8082
query.max-memory=5GB
query.max-memory-per-node=1GB
discovery-server.enabled=true
discovery.uri=http://coordinator:8082
presto.version=0.297-SNAPSHOT-b238a23


native-execution-enabled=true
optimizer.optimize-hash-generation=false
regex-library=RE2J
use-alternative-function-signatures=true
# experimental.table-writer-merge-operator-enabled=false
# guice.require-explicit-bindings=false