# node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
# node.environment=testing
# node.internal-address=127.0.0.1
# node.location=testing-location


node.environment=development
node.id=coordinator
node.data-dir=/opt/presto/data