discovery.uri=http://coordinator:8082
http-server.http.port=7777
presto.version=0.297-SNAPSHOT-b238a23

system-memory-gb=46
query-memory-gb=38
query.max-memory-per-node=38GB

memory-arbitrator-kind=SHARED
shared-arbitrator.global-arbitration-enabled=true

spill-enabled=true
join-spill-enabled=true
aggregation-spill-enabled=true
order-by-spill-enabled=true
max-spill-bytes=500GB

exchange.http-client.request-timeout=5m
exchange.http-client.connect-timeout=30s

system-mem-pushback-enabled=true
system-mem-limit-gb=48

enable-memory-leak-check=true
experimental.spiller-spill-path=/data
